name: gtd-attack-success
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - shap
  - matplotlib
  - seaborn
  - joblib
  - openpyxl
  - pyarrow
  - pytorch
  - jupyter
  - notebook
  - pip
